# Generated by Django 5.1.1 on 2024-09-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_remove_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
